### ISSUE TITLE
V13.1.2 Unexpected entity type "umbraco-commerce-country"

### ISSUE THREAD

**Issue by BenWhite27** [umbraco/Umbraco.Commerce.Deploy#11]
I'm receiving the following exception and errors when cloning my cloud project down to my PC on first run/install.  I believe this started after adding some country/region specific tax rates to the store.

```
The source environment has thrown a Umbraco.Deploy.Core.Exceptions.ProcessArtifactException with message: 
Process pass #4 failed for artifact umb://umbraco-commerce-tax-class/70e09823b778432581c9018ee1abbe25. 
It might have been caused by an inner System.Exception with message: Unexpected entity type "umbraco-commerce-country".

The following artifacts might be involved:

umb://umbraco-commerce-tax-class/70e09823b778432581c9018ee1abbe25
```

More details from deploy.log
```
EXCEPTION:

Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #4 failed for artifact umb://umbraco-commerce-tax-class/70e09823b778432581c9018ee1abbe25.
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, String ownerEmail, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.Proceed(List`1 artifacts, Manifest manifest)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)

INNER:
	System.Exception: Unexpected entity type "umbraco-commerce-country".
	   at Umbraco.Commerce.Infrastructure.Resiliency.PollyExecutionStrategyBase.Execute[TResult](Func`1 operation, Func`1 verifySucceeded)
	   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(IUnitOfWorkOptions options, Action`1 action)
	   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(Action`1 action)
	   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceTaxClassServiceConnector.Pass4(ArtifactDeployState`2 state, IDeployContext context)
	   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceTaxClassServiceConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
	   at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)
	   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, String ownerEmail, IDeployContext context, CancellationToken token)
```
Hope that helps.

**Comment by BenWhite27** [comment]
Looking at the UDA file itself, it appears that a `RegionUDI` has a Country UDI assigned? (**Line 8** below)
```
{
  "Name": "Standard",
  "Alias": "standard",
  "DefaultTaxRate": 0.2,
  "CountryRegionTaxRates": [
    {
      "CountryUdi": "umb://umbraco-commerce-country/6bdf15708db541a6894e018ee1abbe03",
      "RegionUdi": "umb://umbraco-commerce-country/6bdf15708db541a6894e018ee1abbe03"
    },
    {
      "CountryUdi": "umb://umbraco-commerce-country/6bdf15708db541a6894e018ee1abbe03",
      "TaxRate": 0.2
    }
  ],
  "StoreUdi": "umb://umbraco-commerce-store/79525eb99875475f9bbf018ee1abbd5b",
  "Udi": "umb://umbraco-commerce-tax-class/70e09823b778432581c9018ee1abbe25",
  "Dependencies": [
    {
      "Udi": "umb://umbraco-commerce-store/79525eb99875475f9bbf018ee1abbd5b",
      "Mode": "Exist"
    },
    {
      "Udi": "umb://umbraco-commerce-country/6bdf15708db541a6894e018ee1abbe03",
      "Mode": "Exist"
    }
  ],
  "__type": "Umbraco.Commerce.Deploy,Umbraco.Commerce.Deploy.Artifacts.TaxClassArtifact",
  "__version": "13.1.1"
}
```

Looking at the code, this line stands out.
https://github.com/umbraco/Umbraco.Commerce.Deploy/blob/3425c8c046b501d45b05cf3d318c697ce36155ba/src/Umbraco.Commerce.Deploy/Connectors/ServiceConnectors/UmbracoCommerceTaxClassServiceConnector.cs#L84

**Comment by BenWhite27** [comment]
@mattbrailsford I'm happy to do a PR for this one but not sure which branch it should go in?  I'm also not that familiar with Deploy's internals so unsure if there's more than just the one line above that needs changing?

**Comment by mattbrailsford** [comment]
Oooh, a PR would be amazing. What version of Umbraco Commerce Deploy are you using? And yes, I think that should be the right update for the error.

**Comment by BenWhite27** [comment]
I've got v13.1.2 installed at the moment, waiting on a few more fixes to Umbraco v14 before I upgrade.

**Comment by mattbrailsford** [comment]
That's cool, then if you want to target your PR against the `support/13.x` branch I can take care of the rest

**Comment by mattbrailsford** [comment]
If you want to give it a try there is a 13.1.3--preview.3 on [our nightly feed](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds). I'll push our a final release this afternoon regardless.

**Comment by BenWhite27** [comment]
Thanks Matt!  I'll try it out.

**Comment by BenWhite27** [comment]
Just checking back to say deploying the preview package in the cloud environment has worked fine.  UDA files are now correct and setting up new cloud/local environments works again.

**Comment by mattbrailsford** [comment]
Excellent! I'll get a full release pushed out shortly. Thanks for confirming

**Comment by mattbrailsford** [comment]
Umbraco Commerce Deploy 13.1.3 is on NuGet now. Thanks again for the PR 👍
