### ISSUE TITLE
Deploy fails with "The INSERT statement conflicted with the FOREIGN KEY constraint"

### ISSUE THREAD

**Issue by robertjf** [umbraco/Umbraco.Commerce.Deploy#4]
After deploying changes including Umbraco Commerce to the development environment on Umbraco Cloud, the Deploy process "Update Umbraco Schema From Data Files" is failing with the following error:

```json
{
  "Date": "2023-10-23T01:23:32.642971+00:00",
  "Message": "The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_umbracoCommerceCountry_umbracoCommerceStore\". The conflict occurred in database \"h0beaaxheyk\", table \"dbo.umbracoCommerceStore\", column 'id'.\r\nThe statement has been terminated.",
  "Ex": {
    "ClassName": "Microsoft.Data.SqlClient.SqlException",
    "Message": "The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_umbracoCommerceCountry_umbracoCommerceStore\". The conflict occurred in database \"h0beaaxheyk\", table \"dbo.umbracoCommerceStore\", column 'id'.\r\nThe statement has been terminated.",
    "Data": {
      "HelpLink.ProdName": "Microsoft SQL Server",
      "HelpLink.ProdVer": "12.00.5349",
      "HelpLink.EvtSrc": "MSSQLServer",
      "HelpLink.EvtID": "547",
      "HelpLink.BaseHelpUrl": "https://go.microsoft.com/fwlink",
      "HelpLink.LinkId": "20476",
      "OriginalClientConnectionId": "a0b81f6c-4d1f-4259-8d72-907a011efaf3",
      "RoutingDestination": "a3411a75c024.tr42556.eastus1-a.worker.database.windows.net,11022",
      "SqlError 1": "Microsoft.Data.SqlClient.SqlError: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_umbracoCommerceCountry_umbracoCommerceStore\". The conflict occurred in database \"h0beaaxheyk\", table \"dbo.umbracoCommerceStore\", column 'id'.",
      "SqlError 2": "Microsoft.Data.SqlClient.SqlError: The statement has been terminated."
    },
    "InnerException": null,
    "HelpURL": null,
    "StackTraceString": "   at Umbraco.Commerce.Infrastructure.Resiliency.PollyExecutionStrategyBase.Execute[TResult](Func`1 operation, Func`1 verifySucceeded)\r\n   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(IUnitOfWorkOptions options, Action`1 action)\r\n   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(Action`1 action)\r\n   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceCountryServiceConnector.Pass2(ArtifactDeployState`2 state, IDeployContext context)\r\n   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceCountryServiceConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)\r\n   at Umbraco.Deploy.Infrastructure.Connectors.ServiceConnectors.ServiceConnectorBase`3.Process(ArtifactDeployState dart, IDeployContext context, Int32 pass)\r\n   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)",
    "RemoteStackTraceString": null,
    "RemoteStackIndex": 0,
    "ExceptionMethod": null,
    "HResult": -2146232060,
    "Source": "Core Microsoft SqlClient Data Provider",
    "WatsonBuckets": null,
    "Errors": null,
    "ClientConnectionId": "ea4986ef-8a19-4f33-b9d7-e40f063e160b"
  },
  "Sender": "Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem"
}
```

**Comment by robertjf** [comment]
When I look in the database, the `umbracoCommerceStore` table is empty - I wonder whether this is a prioritisation issue?  I.e., the store record must be created first but isn't?

**Comment by mattbrailsford** [comment]
It shouldn't be as if that was the case it would mean that it should never have worked. Are there any errors in your error log that might suggest the store node failed to save?

**Comment by robertjf** [comment]
I can give you access to the Cloud Project if you want?  Otherwise I can check in a couple of hours

**Comment by robertjf** [comment]
@mattbrailsford all I get in the logs is this:

```
Work "969d8c8d-ec6c-4ea8-ba40-50cd31945889" has failed.

Umbraco.Deploy.Core.Exceptions.ProcessArtifactException: Process pass #2 failed for artifact umb://umbraco-commerce-country/34498ce4ac1e428fab06018ab4e3e251.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): The INSERT statement conflicted with the FOREIGN KEY constraint "FK_umbracoCommerceCountry_umbracoCommerceStore". The conflict occurred in database "<DATABASE_NAME>", table "dbo.umbracoCommerceStore", column 'id'.
The statement has been terminated.
   at Umbraco.Commerce.Infrastructure.Resiliency.PollyExecutionStrategyBase.Execute[TResult](Func`1 operation, Func`1 verifySucceeded)
   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(IUnitOfWorkOptions options, Action`1 action)
   at Umbraco.Commerce.Core.UmbracoCommerceUnitOfWorkProvider.Execute(Action`1 action)
   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceCountryServiceConnector.Pass2(ArtifactDeployState`2 state, IDeployContext context)
   at Umbraco.Commerce.Deploy.Connectors.ServiceConnectors.UmbracoCommerceCountryServiceConnector.Process(ArtifactDeployState`2 state, IDeployContext context, Int32 pass)
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
ClientConnectionId:fa4d6e7f-dbc5-4f73-be34-11b5a108db96
Error Number:547,State:0,Class:16
ClientConnectionId before routing:e94fc290-0aaf-476b-ba03-0f46122ebee5
Routing Destination:a3411a75c024.tr42556.eastus1-a.worker.database.windows.net,11022
   --- End of inner exception stack trace ---
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessArtifacts(IEnumerable`1 arts, IDeployContext context, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Environments.CurrentEnvironment.ProcessPackageAsync(Guid sessionId, Package package, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.Proceed(List`1 artifacts, Manifest manifest)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsyncSub(IWorkContext context, List`1 resume, CancellationToken token)
   at Umbraco.Deploy.Infrastructure.Work.WorkItems.DiskReadWorkItem.ExecuteAsync(IWorkContext context, CancellationToken token)
```

There's nothing about the store failing to save at all.

**Comment by Frost117** [comment]
I believe the extraction failed due to the umbraco-commerce-country.uda was looking for its dependency of umbraco-commerce-store.uda.

The store file was not present at the environment. 

It was solved by re-saving the commerce store locally, exporting uda schemas and pushing all of them to the env.

After that the extraction succeeded.

**Comment by mattbrailsford** [comment]
Excellent work @Frost117 I'll consider this issues closed.
